name: release
on:
  push:
    tags: ['v*']
jobs:
  release:
    uses: tyleryancey/light-workspace/.github/workflows/reusable-release.yml@main
    permissions:
      contents: write
    secrets: inherit
