name: reusable-check
on:
  workflow_call: {}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - uses: android-actions/setup-android@v3
      - name: Gradle check
        run: ./gradlew check
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PACKAGES_USER: ${{ github.actor }}
          GH_PACKAGES_TOKEN: ${{ secrets.LIGHT_CI_PAT }}
